name: Bug Report
description: File a bug report.
title: "[Bug]: "
labels: ["bug", "Backend Dependencies"]
assignees:
  - octocat
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen? Feel free to use media attachments.
      placeholder: Tell us what you see!
      value: "A bug happened!"
    validations:
      required: true
  - type: textarea
    id: steps
    attributes: 
      label: Steps to Reproduce
    validations:
      required: true
  - type: dropdown
    id: os
    attributes:
      label: What browsers are you seeing the problem on?
      multiple: true
      options: 
        - iOS
        - Android
        - Web/m-Web
    validations: 
      required: true
  - type: dropdown
    id: browsers
    attributes:
      label: What browsers are you seeing the problem on?
      multiple: true
      options:
        - Firefox
        - Chrome
        - Safari
        - Microsoft Edge
  
  
