name: Feature Request
description: Feature Request.
title: "[Feature Request]: "
labels: ["triage"]

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this feature request!
  - type: textarea
    id: problem_statement
    attributes:
      label: Problem Statement
      description: What problem is this feature solving? Why is it needed?
    validations:
      required: true

  - type: textarea
    id: bussiness_document
    attributes: 
      label: Bussiness Document
      description: Product Requirement Document
      placeholder: This could be input or link to a document covering the details that might be necessary. Example Target Audience, Primary use case, Value Proposition, Success Metrics.
    validations:
      required: false
      
  - type: textarea
    id: user_stories
    attributes:
      label: User Stories
      description: Write as many user stories as you can!
      placeholder: As a [type of user], I want to [perform an action] so that [I can achieve a goal].
    validations:
      required: true
  - type: textarea
    id: acceptance_criteria
    attributes:
      label: Acceptance Criteria
      description: Clearly define the specific conditions that must be met for this feature to be considered done from both business and technical perspectives. These criteria should be clear, measurable, and actionable for both teams. 
      placeholder: The feature should allow users to log in using their Google account. The system should handle at least 100 concurrent logins without degradation in performance.
    validations:
      required: true
 
